#! /bin/bash

name="mktar"
version="2.0"
read -r -d '' help_message <<-EOF
	Make an archive
	Usage: mktar --name=OUTFILE [OPTIONS] FILE..
	Options:
	 --checksum=ALGO             create checksum with [none|sha1|sha256|sha512]
	 -d=DIR,                     working directory
	   --from-directory=DIR,
	   --working-directory=DIR
	 -h, --help                  print this message
	 -n=FILE, --name=FILE        name of archive
	 -p=PASS, --passphrase=PASS  use plaintext passphrase
	 -q, --quiet                 suppress error messages and prompts
	 -v, --verbose               show additional messages
	 -V, --version               print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myarchivelib.bash

ValidateChecksumArgument() {
  case "${1}" in
  none)   return 0;;
  sha1)   return 0;;
  sha256) return 0;;
  sha512) return 0;;
  *)      return 1;;
  esac
}

positional=()
archive_fn=""
checksum="none"
passwd=""
quiet=0
verbose=0
working_directory="."

while [[ "${#}" -gt 0 ]]; do
  case "${1}" in

  --checksum=*)
    IFS='=' read -r flag extract <<<"${1}"
    new="${extract}"
    if [[ -z "${new}" ]] || ! ValidateChecksumArgument "${new}"; then
      Error "parser: cannot use checksum algorithm '${new}'"
    else
      Debug "parser: --checksum='${new}' (was ${checksum})"
      checksum="${new}"
    fi
    shift
    ;;

  --checksum)
    new="${2}"
    if [[ -z "${new}" ]] || ! ValidateChecksumArgument "${new}"; then
      Error "parser: cannot use checksum algorithm '${new}'"
    else
      Debug "parser: --checksum='${new}' (was ${checksum})"
      checksum="${new}"
    fi
    shift; shift
    ;;

  -d=*|--from-directory=*|--working-directory=*)
    IFS='=' read -r flag extract <<<"${1}"
    Debug "parser: --working-directory='${extract}' (was ${working_directory})"
    working_directory="${extract}"
    shift
    ;;

  -d|--from-directory|--working-directory)
    Debug "parser: --working-directory='${2}' (was ${working_directory})"
    working_directory="${2}"
    shift; shift
    ;;

  -h|--help)
    Help
    shift
    ;;

  -n=*|--name=*)
    IFS='=' read -r flag extract <<<"${1}"
    Debug "parser: --name='${extract}' (was ${archive_fn})"
    archive_fn="${extract}"
    shift
    ;;

  -n|--name)
    Debug "parser: --name='${2}' (was ${archive_fn})"
    archive_fn="${2}"
    shift; shift
    ;;

  -p=*|--passwd=*|--passphrase=*)
    #NOTE: Normally would emit a message with Debug, but that seems like a bad
    #      idea here.
    IFS='=' read -r flag extract <<<"${1}"
    passwd="${extract}"
    shift
    ;;

  -p|--passwd|--passphrase)
    #NOTE: Normally would emit a message with Debug, but that seems like a bad
    #      idea here.
    passwd="${2}"
    shift; shift
    ;;

  -q|--quiet)
    #NOTE: Normally would emit a message with Debug, but the user is
    #      specifically requesting that we do not.
    quiet=1
    shift
    ;;

  -v|--verbose)
    Debug "parser: --verbose=1 (was ${verbose})"
    verbose=1
    shift
    ;;

  -V|--version)
    Version
    ;;

  *)
    Debug "parser: '${1}' appended to positional arguments"
    positional+=("$1")
    shift
    ;;
  esac
done

RequirePositionalArguments


# Part 1: Handle archive file.
if [[ -z "${archive_fn}" ]]; then
  Usage
fi

archive_path="$(FileAbsolute "${archive_fn}")"
if [[ -z "${archive_path}" ]]; then
  exit 1
fi

if ! SupportedArchive "${archive_fn}"; then
  Fatal "file '${archive_fn}' is not a supported archive"

elif [[ -e "${archive_path}" ]]; then

  #NOTE: Not really an issue if we overwrite, but this mistake happens often
  #      enough (to me) that I want this bubblewrap built in.
  if ArrayContains "${checksum_fn}" "${positional[@]}"; then
    Fatal "file '${archive_fn}' is both an input and output"

  elif ! PromptOverwrite "${archive_fn}"; then
    exit 1
  fi


  if ! /usr/bin/rm "${archive_path}"; then
    Fatal "failed to overwrite file '${archive_fn}'"

  fi
fi


# Part 2: Handle working directory.
if [[ ! -d "${working_directory}" ]]; then
  Fatal "no such directory '${working_directory}'"
fi

path="$(FileAbsolute "${working_directory}")"
if [[ -z "${path}" ]]; then
  exit 1
fi

#NOTE: Directory already validated, so who knows why this would fail? Just
#      report it to the user.
if ! cd "${path}"; then
  Fatal "failed to enter directory '${working_directory}'"
fi

if [[ -z "${archive_fn}" ]]; then
  Usage
fi


# Part 3: Interpret checksum request.
if [[ "${checksum}" != "none" ]]; then
  checksum_fn="$(FileBasename "${archive_fn}").${checksum}"

  checksum_path="$(FileAbsolute "${checksum_fn}")"
  if [[ -z "${checksum_path}" ]]; then
    exit 1
  fi

  if [[ -e "${checksum_path}" ]]; then
    if ArrayContains "${checksum_fn}" "${positional[@]}"; then
      Fatal "file '${checksum_fn}' is both an input and output"
    elif ! PromptOverwrite "${checksum_fn}"; then
      exit 1
    fi

    if ! /usr/bin/rm "${checksum_path}"; then
      Fatal "failed to overwrite file '${checksum_fn}'"
    fi
  fi
fi


# Part 4: Make archive.
code=0

if [[ -z "${passwd}" ]]; then
  if ! MkArchive "${archive_fn}" "${positional[@]}"; then
    code=1
  fi

else
  if ! MkArchivePlaintext "${passwd}" "${archive_fn}" "${positional[@]}"; then
    code=1
  fi

fi

if [[ "${code}" -eq 0 ]] && [[ "${checksum}" != "none" ]]; then
  if ! MkSha "${checksum}" "${archive_fn}" "${checksum_fn}"; then
    code=1
  fi
fi

exit "$code"

