#!/bin/bash

name="rmtar"
version="1.1"
help_message=$(/usr/bin/cat <<-EOF
	Delete archives
	Usage: rmtar [OPTIONS] FILE..
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF
)

. /usr/local/lib/mylib.bash
. /usr/local/lib/myarchivelib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

code=0

for file in "${positional[@]}"; do
  if ! SupportedArchive "${file}"; then
    Debug "file '{$file}' is not a supported archive, ignoring..."

  elif [ ! -e "${file}" ]; then
    Error "no such file '${file}'"
    code=1

  elif ! /usr/bin/rm "${file}"; then
    code=1
  fi

done

exit "${code}"

