#!/bin/bash

name="untar"
version="1.3"
help_message=$(/usr/bin/cat <<-EOF
	Extract files from an archive
	Usage: untar [OPTIONS] FILE..
	Options:
	 -h, --help                  print this message and exit
	 -d=DIR,                     working directory
	   --from-directory=DIR,
	   --working-directory=DIR
	 -p PASS, --passphrase PASS  use plaintext passphrase
	 -q, --quiet                 suppress error messages
	 -v, --version               print version number and exit
EOF
)

. /usr/local/lib/mylib.bash
. /usr/local/lib/myarchivelib.bash

positional=()
passwd=""
quiet=0
verbose=0
working_directory="."

while [[ "${#}" -gt 0 ]]; do
  case "${1}" in

  -d=*|--to-directory=*|--working-directory=*)
    IFS='=' read -r flag extract <<<"${1}"
    Debug "parser: --working-directory='${extract}' (was ${working_directory})"
    working_directory="${extract}"
    shift
    ;;

  -d|--to-directory|--working-directory)
    Debug "parser: --working-directory='${2}' (was ${working_directory})"
    working_directory="${2}"
    shift; shift
    ;;

  -h|--help)
    Help
    shift
    ;;

  -p=*|--passwd=*|--passphrase=*)
    #NOTE: Normally would emit a message with Debug, but that seems like a bad
    #      idea here.
    IFS='=' read -r flag extract <<<"${1}"
    passwd="${extract}"
    shift
    ;;

  -p|--passwd|--passphrase)
    #NOTE: Normally would emit a message with Debug, but that seems like a bad
    #      idea here.
    passwd="${2}"
    shift; shift
    ;;

  -q|--quiet)
    #NOTE: Normally would emit a message with Debug, but the user is
    #      specifically requesting that we do not.
    quiet=1
    shift
    ;;

  -v|--verbose)
    Debug "parser: --verbose=1 (was ${verbose})"
    verbose=1
    shift
    ;;

  -V|--version)
    Version
    ;;

  *)
    Debug "parser: '${1}' appended to positional arguments"
    positional+=("$1")
    shift
    ;;
  esac
done

RequirePositionalArguments


# Part 1: Handle archive files.
archive_fns=()

for archive_fn in "${positional[@]}"; do
  if [[ ! -e "${archive_fn}" ]]; then
    Fatal "no such file '${archive_fn}'"
  fi

  archive_path="$(FileAbsolute "${archive_fn}")"
  if [[ -z "${archive_path}" ]]; then
    exit 1
  fi

  if ! SupportedArchive "${archive_fn}"; then
    Fatal "file '${archive_fn}' is not a supported archive"
  fi

  archive_fns+=("${archive_path}")

done


# Part 2: Handle working directory.
if [[ ! -d "${working_directory}" ]]; then
  Fatal "no such directory '${working_directory}'"
fi

path="$(FileAbsolute "${working_directory}")"
if [[ -z "${path}" ]]; then
  exit 1
fi

#NOTE: Directory already validated, so who knows why this would fail? Just
#      report it to the user.
if ! cd "${path}"; then
  Fatal "failed to enter directory '${working_directory}'"
fi


# Part 3: Extract files from archives.
code=0

for archive_fn in "${archive_fns[@]}"; do

  if [[ -z "${passwd}" ]]; then
    if ! ExtractArchive "${archive_fn}"; then
      code=1
    fi
  else
    if ! ExtractArchivePlaintext "${passwd}" "${archive_fn}"; then
      code=1
    fi
  fi
done

exit "${code}"

