#!/bin/bash

name="hugo-timestamp"
version="1.0"
read -r -d '' help_message <<-EOF
	Set a timestamp into a Hugo content file
	Usage: hugo-timestamp [OPTIONS] TARGET DATETIME
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

_ed_append_date() {
  ed -s "${1}" <<EOF
/^title:/a
date: "${2}"
.
w
q
EOF
}

_ed_overwrite_date() {
  ed -s "${1}" <<EOF
g/^date:/c
i
date: "${2}"
.
w
q
EOF
}

filename="${positional[0]}"
newdate="${positional[1]}"

if [[ ! -f "${filename}" ]]; then
  Fatal "no such file '${filename}'"

olddate="$(hugo-extract-timestamp "${filename}")"

if [[ -z "${olddate}" ]]; then
  Debug "no timestamp, appending..."

  _ed_append_date "${filename}" "${newdate}"

else
  Debug "timestamp found (${olddate}), overwriting..."

  _ed_overwrite_date "${filename}" "${newdate}"

fi


