#!/bin/bash

name="hugo-extract-timestamp"
version="1.0"
read -r -d '' help_message <<-EOF
	Extract a date/timestamp from Hugo content files
	Usage: hugo-extract-timestamp [OPTIONS] TARGETS..
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

code=0

for filename in "${positional[@]}"; do

  if [[ ! -f "${filename}" ]]; then
    Error "no such file '${filename}'"
    code=1

    #NOTE: Emit an empty line for consistency between number of inputs and
    #      outputs.
    /usr/bin/echo

  elif ! FileMatches "^date:.*" "${filename}"; then
    Debug "no timestamp in '${filename}'"
    code=1

    #NOTE: Emit an empty line for consistency between number of inputs and
    #      outputs.
    /usr/bin/echo

  else
    /usr/bin/grep "${filename}" --regexp="^date:" \
      | /usr/bin/sed --expression="s/^date: *//"

  fi
done

exit "${code}"

