#!/bin/bash

name="hugo-date"
version="1.1"
read -r -d '' help_message <<-EOF
	Print current date and time in the Hugo/Go format
	Usage: hugo-date [OPTIONS]
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

/usr/bin/date +%FT%T%:z

