#!/bin/bash

name="hugo-bump"
version="1.0"
read -r -d '' help_message <<-EOF
	Bump the date in Hugo content files
	Usage: hugo-bump [OPTIONS] [TARGETS ..]
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

source /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

# error if no filenames given
if [[ ${#positional[@]} -eq 0 ]]; then
  usage_msg
fi

bump() {
  ed -s "$1" <<EOF
g/^date:/c
i
date: "$2"
.
w
EOF
}

code=0
newdate="$(hugo-date)"
for filename in "${positional[@]}"; do
  if [[ ! -f "$filename" ]]; then
    nonfatal_error_msg "No such file '$filename'"
    code=1
  else
    if [[ "$verbose" -eq 1 ]]; then
      olddate="$(/usr/bin/grep "$filename" --regexp="^date:")"
      debug_msg "replacing ${olddate}..."
    fi
    bump "$filename" "$newdate"
  fi
done

exit "$code"

