#!/bin/sh

name="hugo-date"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	Print current date and time in the Hugo/Go format
	Usage: hugo-date
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

date +%FT%T%:z

