#!/bin/bash

name="hugo-post"
version="1.1"
read -r -d '' help_message <<-EOF
	Create a new Hugo post file
	Usage: hugo-post [OPTIONS] TITLE
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

if [[ "$(pwd)" =~ .*/posts ]]; then
  dirname="$(FileAbsolute ".")"

elif [[ "$(pwd)" =~ .*/content ]] && [[ -d "posts" ]]; then
  dirname="$(FileAbsolute "posts")"

elif [[ -d "content" ]] && [[ -d "content/posts" ]]; then
  dirname="$(FileAbsolute "content/posts")"

else
  Fatal "not in a Hugo project directory"

fi
if [[ -z "${dirname}" ]]; then
  exit 1
fi

title="${positional[0]}"
filename="$(FileSafename "${title}").md"
path="${dirname}/${filename}"
Debug "resolved '${title}' to '${path}'"

if [ -f "${path}" ]; then
  Fatal "file '${path}' already exists"

elif [ -d "${path}" ]; then
  Fatal "'${path}' already exists and is a directory"

fi

# create new file
hugo-new --title="${title}" >"${path}"

