#!/bin/bash

name="hugo-bump"
version="1.0"
read -r -d '' help_message <<-EOF
	Bump the date in Hugo content files
	Usage: hugo-bump [OPTIONS] TARGETS..
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

bump() {
  /usr/bin/ed -s "${1}" <<EOF
g/^date:/c
i
date: "${2}"
.
w
EOF
}

code=0
newdate="$(hugo-date)"

for filename in "${positional[@]}"; do
  if [[ ! -f "${filename}" ]]; then
    Error "no such file '${filename}'"
    code=1

  else
    Debug "replacing $(/usr/bin/grep "${filename}" --regexp="^date:")..."

    bump "${filename}" "${newdate}"

  fi
done

exit "${code}"

