#!/bin/bash

name="moincase"
version="1.0"
read -r -d '' help_message <<-EOF
	Adjust casing for a MoinMoin-markup title
	Usage: moincase [OPTIONS] TITLE
	Note:  Quoted elements in TITLE are treated as a single word, and therefore may not be adjusted
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

# NOTE: The (bash) shell expansion `${parameter^pattern}` converts lowercase
# letters matching `pattern` to uppercase. If `pattern` is omitted, the default
# behavior is the wildcard `?` (any single character). Simply put, the first
# letter of every word is capitalized.

# NOTE: The array subscript `*` causes all members to be joined by the internal
# field separator (IFS). Setting the IFS (in a subshell!) to nothing simply
# concatenates the members.

(IFS=; echo "${positional[*]^}")

