#!/bin/bash

name="overdot"
version="1.0"
read -r -d '' help_message <<-EOF
	Dump all possible overdot'ed ASCII letters
	Usage: overdot [OPTIONS]
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

( \
  for n in $(/usr/bin/seq 65 90); do
    /usr/bin/printf -- "\x$(dec2hex $n)\xCC\x87\n"
  done
  for n in $(/usr/bin/seq 97 122); do
    /usr/bin/printf -- "\x$(dec2hex $n)\xCC\x87\n"
  done
) | /usr/bin/column

