#!/bin/sh

# whiched
# =======
# USAGE: whiched PROGRAM
#
# Open a program in `$EDITOR`

help_msg() {
  cat <<-EOF
	Open a program with your editor
	Usage: whiched PROGRAM [OPTIONS]
	Options:
	 -h, --help: print this message
	EOF
  exit 1
}

err_msg() {
  (>&2 echo "$1")
  exit 1
}

for i in "$@"; do
  case $i in
    -h|--help) help_msg;;
  esac
done

if [ "$#" -lt 1 ]; then
  err_msg "Usage: whiched PROGRAM [OPTIONS]"
fi

BIN=$(which "$1" 2>/dev/null)
if [ -z "$BIN" ]; then
  err_msg "No program '${1}'"
fi

ED=${EDITOR:-ed}
"$ED" "$BIN"

