#!/bin/sh

name="docker-up"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	Start a Docker container using './docker-compose.yml'.
	Usage: docker-up
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

docker-compose up --detach

