#!/bin/sh

name="docker-get-exited"
version="1.1"
help_message=$(/usr/bin/cat <<-EOF
	List all exited Docker containers' IDs
	Usage: docker-get-exited
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

docker ps --format "{{.ID}}" --filter "exited=1" --filter "is-task=false" --all

