#!/bin/sh

name="docker-restart"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	Restart all exited Docker containers
	Usage: docker-restart
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

for container in $(docker-get-exited); do
  docker start "$container"
done

