#!/bin/bash

name="resetx"
version="1.1"
read -r -d '' help_message <<-EOF
	Reset the X11 server
	Usage: resetx
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

if ! checkx; then
  Fatal "no running X11 server"
fi

if [ ! -f "${HOME}/.xinitrc" ]; then
  Fatal "cannot find X11 configuration (should be '~/.xinitrc')"
fi

xrandr_cmd="$(/usr/bin/grep --regexp '^xrandr ' "${HOME}/.xinitrc")"
Debug "${xrandr_cmd}"

sudo "${xrandr_cmd}"

