#!/bin/bash

name="whisper"
version="1.1"
read -r -d '' help_message <<-EOF
	Non-serious text-to-speech
	Usage: whisper [OPTIONS] [MESSAGE..]
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages and prompts
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

message="${positional[@]}"
if [ "${#positional[@]}" -eq 0 ]; then
  message="present day <break time='1000ms'/> present time."
fi

exec /usr/bin/espeak -v +whisper -s 8 -m "${message}" 2>/dev/null

