#!/bin/sh

name="vpn-on"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	Start an OpenVPN connection using '\$MYUTILS_OPENVPN_CONF'
	Usage: vpn-on
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

sudo openvpn --config "$MYUTILS_OPENVPN_CONF" --daemon

