#!/bin/bash

name="ctdir"
version="1.1"
read -r -d '' help_message <<-EOF
	Count entries in target directory(ies)
	Usage: ctdir [OPTIONS] TARGET..
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

code=0

for dir in "${positional[@]}"; do
  if [[ ! -d "${dir}" ]]; then
    Error "no such directory '${dir}'"
    code=1

    #NOTE: Emit an empty line for consistency between number of inputs and
    #      outputs.
    /usr/bin/echo

  else
    path="$(FileAbsolute "${dir}")"
    if [[ -z "${path}" ]]; then
      exit 1
    fi

    Debug "resolved '${dir}' to '${path}'"

    /usr/bin/ls -1A "${path}" 2>/dev/null | wc -l

  fi
done

exit "${code}"

