#!/bin/bash

name="dired"
version="1.1"
read -r -d '' help_message <<-EOF
	Open Emacs in dired mode
	Usage: dired [TARGET]
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

if [[ "${#positional[@]}" -eq 0 ]]; then
  exec emacs -nw .

elif [[ ! -d "${positional[0]}" ]]; then
  Fatal "no such directory '${positional[0]}'"

else
  exec emacs -nw "${positional[0]}"

fi

