#!/bin/bash

name="enumerate"
version="1.1"
read -r -d '' help_message <<-EOF
	Rename files in a target directory (or current directory) sequentially
	Usage: enumerate [OPTIONS] [TARGET]
	Options:
	 -d, --dry-run     print, not execute, changes (Default)
	 -f=P, --filter=P  filter targets with filename pattern P
	 -h, --help        print this message and exit
	 -q, --quiet       suppress error messages
	 -s=N, --start=N   start enumeration at N (Default: 1)
	 -S=N, --step=N    step enumeration by N (Default: 1)
	 -v, --verbose     show additional messages
	 -V, --version     print version number and exit
	 -w=N, --width=N   rename files to numbers N wide (Default: 4)
	 -x, --execute     execute changes
EOF

source /usr/local/lib/mylib.bash

positional=()
execute=0
filter="*"
enum_start=1
enum_step=1
width=4
quiet=0
verbose=0

while [[ "${#}" -gt 0 ]]; do
  case "${1}" in

  -f=*|--filter=*)
    IFS='=' read -r flag extract <<<"${1}"
    Debug "parser: --filter='${extract}' (was ${filter})"
    filter="${extract}"
    shift
    ;;

  -f|--filter)
    Debug "parser: --filter='${2}' (was ${filter})"
    filter="${2}"
    shift; shift
    ;;

  -h|--help)
    Help
    shift
    ;;

  -q|--quiet)
    #NOTE: Normally would emit a message with Debug, but the user is
    #      specifically requesting that we do not.
    quiet=1
    shift
    ;;

  -s=*|--start=*)
    IFS='=' read -r flag extract <<<"${1}"
    if ! IsNatural "${extract}"; then
      Error "parser: cannot start at '${extract}' (not an integer >= 0)"
    else
      Debug "parser: --start=${extract} (was ${enum_start})"
      enum_start="${extract}"
    fi
    shift
    ;;

  -s|--start)
    if ! IsNatural "${2}"; then
      Fatal "parser: cannot start at '${2}' (not an integer >= 0)"
    else
      Debug "parser: --start=${2} (was ${enum_start})"
      enum_start="${2}"
    fi
    shift; shift
    ;;

  -S=*|--step=*)
    IFS='=' read -r flag extract <<<"${1}"
    if ! IsPositiveInteger "${extract}"; then
      Error "parser: cannot step by '${extract}' (not an integer >= 1)"
    else
      Debug "parser: --step=${extract} (was ${enum_step})"
      enum_step="${extract}"
    fi
    shift
    ;;

  -S|--step)
    if ! IsPositiveInteger "${2}"; then
      Fatal "parser: cannot step by '${2}' (not an integer >= 1)"
    else
      Debug "parser: --step=${2} (was ${enum_step})"
      enum_step="${2}"
    fi
    shift; shift
    ;;

  -v|--verbose)
    Debug "parser: --verbose=1 (was ${verbose})"
    verbose=1
    shift
    ;;

  -V|--version)
    Version
    ;;

  -w=*|--width=*)
    IFS='=' read -r flag extract <<<"${1}"
    if ! IsNatural "${extract}"; then
      Error "parser: cannot use width of '${extract}' (not an integer >= 0)"
    else
      Debug "parser: --width=${extract} (was ${width})"
      width="${extract}"
    fi
    shift
    ;;

  -w|--width)
    if ! IsNatural "$2"; then
      Fatal "parser: cannot use width of '${2}' (not an integer >= 0)"
    else
      Debug "parser: --width=${2} (was ${width})"
      width="${2}"
    fi
    shift; shift
    ;;

  -x|--execute)
    Debug "parser: --execute=1 (was ${execute})"
    execute=1
    shift
    ;;

  *)
    Debug "parser: '${1}' appended to positional arguments"
    positional+=("${1}")
    shift
    ;;
  esac
done

dir="$(DirectoryArgumentOrCurrent)"
if [[ -z "${dir}" ]]; then
  exit 1
fi

path="$(FileAbsolute "${dir}")"
if [[ -z "${path}" ]]; then
  exit 1
fi

Debug "resolved '${dir}' to '${path}'"

#NOTE: Directory already validated, so who knows why this would fail? Just
#      report it to the user.
if ! cd "${path}"; then
  Fatal "failed to enter directory '${dir}'"
fi

n="${enum_start}"
s="${enum_step}"
code=0

while IFS= read -r -d '' original_fn; do
  wide_n=$(/usr/bin/printf -- '%0*d\n' "${width}" "${n}")
  enum_fn="${wide_n}.$(FileExtension "$original_fn")"

  if [[ "$execute" -eq 1 ]]; then
    if ! mv "${original_fn}" "${enum_fn}"; then
      code=1
    fi

  else
    /usr/bin/printf -- '#mv %s %s\n' "${original_fn}" "${enum_fn}"

  fi

  n=$((n+s))

done < <(find . -maxdepth 1 -name "${filter}" -type f -printf "%f\0" | sort -z)

exit "${code}"

