#!/bin/bash

name="mkbak"
version="1.0"
read -r -d '' help_message <<-EOF
	Create a backup of a target file
	Usage: mkbak [OPTIONS] TARGET
	Options:
	 -d, --diff            diff files before asking to overwrite
	 -f, --force           overwrite without asking
	 -h, --help            print this message and exit
	 -n=FILE, --name=FILE  name of backup file (Default: TARGET.bak)
	 -q, --quiet           suppress error messages and prompts
	 -v, --verbose         show additional messages
	 -V, --version         print version number and exit
EOF

. /usr/local/lib/mylib.bash

positional=()
quiet=0
verbose=0
force=0
backup_fn=""

while [[ "${#}" -gt 0 ]]; do
  case $1 in

  -d|--diff)
    Debug "parser: --diff=1 (was ${diff})"
    diff=1
    shift
    ;;

  -f|--force)
    Debug "parser: --force=1 (was ${force})"
    force=1
    shift
    ;;

  -h|--help)
    Help
    shift
    ;;

  -n=*|--name=*)
    IFS='=' read -r flag extract <<<"${1}"
    Debug "parser: --name=${extract} (was ${backup_fn})"
    backup_fn="${extract}"
    shift
    ;;

  -n|--name)
    Debug "parser: --name=${2} (was ${backup_fn})"
    backup_fn="${2}"
    shift; shift
    ;;

  -q|--quiet)
    #NOTE: Normally would emit a message with Debug, but the user is
    #      specifically requesting that we do not.
    quiet=1
    shift
    ;;

  -v|--verbose)
    Debug "parser: --verbose=1 (was ${verbose})"
    verbose=1
    shift
    ;;

  -V|--version)
    Version
    ;;

  *)
    Debug "parser: '${1}' appended to positional arguments"
    positional+=("$1")
    shift
    ;;

  esac
done

RequirePositionalArguments

original_fn="${positional[0]}"
if [[ ! -f "$original_fn" ]]; then
  Fatal "no such file '${original_fn}'"
fi

if [[ -z "$backup_fn" ]]; then
  backup_fn="${original_fn}.bak"
fi
Debug "backup to '${backup_fn}'"

code=0

# Backup doesn't exist already, so make it.
if [[ ! -f "$backup_fn" ]]; then
  /usr/bin/cp "$original_fn" "$backup_fn"
  code="$?"

# Backup exists and is unchanged, so notify user.
elif /usr/bin/cmp "$backup_fn" "$original_fn" >/dev/null 2>&1; then
  Print "file '${backup_fn}' already exists and is a copy of '${original_fn}'"

# Quiet flag is set, so unless force flag also set, exit with code 1.
elif [[ $quiet -eq 1 ]]; then
  if [[ "$force" -eq 0 ]]; then
    /usr/bin/cp "$original_fn" "$backup_fn"
    code="$?"
  else
    Fatal "file '${backup_fn}' already exists"
  fi

# Prompt user for final decision.
else
  if [[ "$diff" -eq 1 ]]; then
    /usr/bin/diff --color "$backup_fn" "$original_fn"
  fi

  if ! PromptOverwrite "$backup_fn"; then
    exit 1
  fi

  /usr/bin/cp "$original_fn" "$backup_fn"
  code="$?"

fi

exit "${code}"

