#!/bin/bash

name="rebom"
version="1.1"
read -r -d '' help_message <<-EOF
	Add BOM to a target file
	Usage: rebom TARGET [OPTIONS]
	Options:
	 -h, --help            print this message
	 -q, --quiet           suppress error messages and prompts
	 -v, --verbose         show additional messages
	 -V, --version         print version number and exit
EOF

source /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

# error if no filenames given
if [[ ${#positional[@]} -eq 0 ]]; then
  usage_msg
fi

code=0
files=()
for filename in "${positional[@]}"; do
  if [ ! -f "$filename" ]; then
    nonfatal_error_msg "No such file '$filename'"
    code=1
  else
    files+=("$filename")
  fi
done

# error if no valid filenames given
if [[ ${#files[@]} -eq 0 ]]; then
  exit 1
fi

/usr/bin/printf "\xEF\xBB\xBF"
/usr/bin/cat ${files[@]}

exit "$code"

