#!/bin/bash

name="rmold"
version="1.1"
read -r -d '' help_message <<-EOF
	Delete files older than a year
	Usage: rmold [PATH]
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages and prompts
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
dir="$(DirectoryArgumentOrCurrent)"
if [[ -z "${dir}" ]]; then
  exit 1
fi

path="$(FileAbsolute "${dir}")"
if [[ -z "${path}" ]]; then
  exit 1
fi

Debug "resolved '${dir}' to '${path}'"

find "${path}" -type f -mtime +365 -delete

