#!/bin/bash

name="shebangs"
version="1.1"
read -r -d '' help_message <<-EOF
	Print the shebang line of each executable script
	Usage: shebangs [PATH]
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages and prompts
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
dir="$(DirectoryArgumentOrCurrent)"
if [[ -z "${dir}" ]]; then
  exit 1
fi

path="$(FileAbsolute "${dir}")"
if [[ -z "${path}" ]]; then
  exit 1
fi

Debug "resolved '${dir}' to '${path}'"

# Find all files and sort them.
# Read the lines of file names. For each file name...
#   Print the file name, a colon, and *no newline*.
#   Run `head -n 1` on the file name.
# Filter out any lines of output that don't contain a colon immediately
# followed by a shebang.
# Replace the colon with appropriate whitespace.
while IFS= read -r -d '' fn; do
  /usr/bin/printf -- '%s:' "${fn}"
  /usr/bin/head --lines 1 "${fn}"
done < \
  <(/usr/bin/find "$path" -maxdepth 1 -type f -print0 | /usr/bin/sort -z) \
  | /usr/bin/grep --fixed-strings ':#!' \
  | /usr/bin/column --separator ':' --table

