#!/bin/bash

name="vimsplit"
version="1.1"
read -r -d '' help_message <<-EOF
	Open two files in split windows
	Usage: vimsplit FILE1 FILE2
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages and prompts
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

if [[ "${#positional[@]}" -ne 2 ]]; then
  Fatal "expected 2 arguments (given ${#positional[@]})"
fi

file1="${positional[0]}"
if [[ ! -f "${file1}" ]]; then
  Fatal "no such file '${file1}'"
fi

file2="${positional[1]}"
if [[ ! -f "${file2}" ]]; then
  Fatal "no such file '${file2}'"
fi

#NOTE: vi does not support the cmd option, so minimum default is in fact vim.
visual="${VISUAL:=/usr/bin/vim}"
if ! command -v "${visual}" >/dev/null 2>&1; then
  Fatal "cannot open in visual editor program '${visual}'"
fi

exec "${visual}" "${file1}" --cmd ":sp ${file2}"

