#!/bin/bash

name="whichhead"
version="1.1"
read -r -d '' help_message <<-EOF
	Print the first 10 lines from a program
	Usage: whichhead [OPTIONS] [PROGRAM ..]
	Options:
	 -h, --help        print this message and exit
	 -n=N, --number=N  print the first N lines (Default: 10)
	 -q, --quiet       suppress error messages
	 -v, --verbose     show additional messages
	 -V, --version     print version number and exit
EOF

. /usr/local/lib/mylib.bash

positional=()
num_lines=10
quiet=0
verbose=0

while [[ "${#}" -gt 0 ]]; do
  case "${1}" in

  -h|--help)
    Help
    shift
    ;;

  -n=*|--number=*)
    IFS='=' read -r flag extract <<<"${1}"
    if ! IsNatural "${extract}"; then
      Error "parser: cannot use line count of '${extract}' (not an integer >= 0)"
    else
      Debug "parser: --number=${extract} (was ${num_lines})"
      num_lines="${extract}"
    fi
    shift
    ;;

  -n|--number)
    if ! IsNatural "${2}"; then
      Error "parser: cannot use line count of '${2}' (not an integer >= 0)"
    else
      Debug "parser: --number=${2} (was ${num_lines})"
      num_lines="${2}"
    fi
    shift; shift
    ;;

  -q|--quiet)
    #NOTE: Normally would emit a message with Debug, but the user is
    #      specifically requesting that we do not.
    quiet=1
    shift
    ;;

  -v|--verbose)
    Debug "parser: --verbose=1 (was ${verbose})"
    verbose=1
    shift
    ;;

  -V|--version)
    Version
    ;;

  *)
    Debug "parser: '${1}' added to positional arguments"
    positional+=("${1}")
    shift
    ;;
  esac
done

RequirePositionalArguments

code=0

for target in "${positional[@]}"; do
  abs_target="$(command -v "$target")"

  if [[ -z "${abs_target}" ]]; then
    Error "no such program '${target}'"
    code=1

  else
    /usr/bin/head "${abs_target}" -n "${num_lines}"

  fi
done

exit "${code}"

