#!/bin/sh

name="whichvi"
version="1.2"
help_message=$(/usr/bin/cat <<-EOF
	Open a program with your visual editor
	Usage: whichvi [OPTIONS] PROGRAM
	Options:
	 -h, --help     print this message
	 -q, --quiet    suppress error messages
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

# NOTE: intentionally does not mirror `whichcat`/`whichhead`
#  1. doesn't make sense to handle multiple files\
#  2. when given no arguments, whiched should follow the lead of which NOT cat

for arg; do
  case "$arg" in
  -q|--quiet)
    #handled in myminiparse.sh
    ;;

  *)
    target=$(command -v "$arg")
    if [ -z "$target" ]; then
      if [ "$quiet" -eq 0 ]; then
        (>&2 /usr/bin/printf "%s: No such program '%s'\n" "$name" "$arg")
      fi
      exit 1
    else
      my_visual=${VISUAL:=/usr/bin/vi}
      if ! command -v "$my_visual" >/dev/null 2>&1; then
        if [ "$quiet" -eq 0 ]; then
          (>&2 /usr/bin/printf "%s: cannot call \$VISUAL '%s', falling back to '/usr/bin/vi'\n" "$name" "$my_visual")
        fi
        my_visual=/usr/bin/vi
      fi
      $my_visual "$target"
      exit $?
    fi
    ;;
  esac
done

if [ "$quiet" -eq 0 ]; then
  (>&2 /usr/bin/printf "Usage: whichvi [OPTIONS] PROGRAM\n")
  exit 1
fi

exit 0

