#!/bin/bash

name="whichvi"
version="1.3"
read -r -d '' help_message <<-EOF
	Open a program with your visual editor
	Usage: whichvi [OPTIONS] PROGRAM
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

target="${positional[0]}"
abs_target="$(command -v "$target" 2>/dev/null)"
if [[ -z "${abs_target}" ]]; then
  Fatal "no such program '${target}'"
fi

visual="${VISUAL:=/usr/bin/vi}"
if ! command -v "${visual}" >/dev/null 2>&1; then
  Fatal "cannot open in visual editor program '${visual}'"
fi

exec "${visual}" "${abs_target}"

