#!/bin/sh

name="whichvi"
version="1.1"
help_message=$(/usr/bin/cat <<-EOF
	Open a program with your visual editor
	Usage: whichvi PROGRAM [OPTIONS]
	Options:
	 -h, --help     print this message
	 -q, --quiet    suppress error messages
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

# NOTE: intentionally does not mirror `whichcat`/`whichhead`; doesn't make
# sense to handle multiple files
for arg; do
  case "$arg" in
  -q|--quiet)
    #ignore these
    ;;

  *)
    # main routine
    target=$(command -v "$arg")
    if [ -z "$target" ]; then
      if [ "$quiet" -eq 0 ]; then
        (>&2 /usr/bin/printf "%s: No such program '%s'\n" "$name" "$arg")
      fi
      exit 1
    else
      my_visual=${VISUAL:=/usr/bin/vi}
      if ! command -v "$my_visual" >/dev/null 2>&1; then
        if [ "$quiet" -eq 0 ]; then
          (>&2 /usr/bin/printf "%s: cannot call \$VISUAL '%s', falling back to '/usr/bin/vi'\n" "$name" "$my_visual")
        fi
        my_visual=/usr/bin/vi
      fi
      $my_visual "$target"
      exit $?
    fi
    ;;
  esac
done

# if have not exited, no program was specified
if [ "$quiet" -eq 0 ]; then
  (>&2 /usr/bin/printf "Usage: whichvi PROGRAM [OPTIONS]\n")
fi
exit 0

