#!/bin/bash

name="whiched"
version="1.3"
read -r -d '' help_message <<-EOF
	Open a program with your editor
	Usage: whiched [OPTIONS] PROGRAM
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

target="${positional[0]}"
abs_target="$(command -v "$target" 2>/dev/null)"
if [[ -z "${abs_target}" ]]; then
  Fatal "no such program '${target}'"
fi

editor="${EDITOR:=/usr/bin/ed}"
if ! command -v "${editor}" >/dev/null 2>&1; then
  Fatal "cannot open in editor program '${editor}'"
fi

exec "${editor}" "${abs_target}"

