#!/bin/bash

name="wttr"
version="1.2"
read -r -d '' help_message <<-EOF
	Wrapper around 'wego' to fix double-wide runes for some fonts
	Usage: wttr [OPTIONS]
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages and prompts
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

wego "${positional[@]}" | sed -e 's/[↘↗↖↙]/ &/g'

