#!/bin/sh

name="android-emulator"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	Start an Android emulator session
	Usage: android-emulator
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

adb start-server
trap "adb kill-server" EXIT

emulator -avd $(emulator -list-avds) -dns-server 8.8.8.8

