export usage_mktar="Usage: mktar --name=OUTFILE [OPTIONS] FILE.."
export usage_rmtar="Usage: rmtar [OPTIONS] FILE.."
export usage_tarcat="Usage: tar-cat [OPTIONS] FILE.."
export usage_tarls="Usage: tar-ls [OPTIONS] FILE.."
export usage_untar="Usage: untar [OPTIONS] FILE.."
export help_mktar_0="Make an archive"
export help_mktar_1="Usage: mktar --name=OUTFILE [OPTIONS] FILE.."
export help_mktar_2="Options:"
export help_mktar_3=" --checksum=ALGO             create checksum with [none|sha1|sha256|sha512]"
export help_mktar_4=" -d=DIR,                     working directory"
export help_mktar_5="   --from-directory=DIR,"
export help_mktar_6="   --working-directory=DIR"
export help_mktar_7=" -h, --help                  print this message"
export help_mktar_8=" -n=FILE, --name=FILE        name of archive"
export help_mktar_9=" -p=PASS, --passphrase=PASS  use plaintext passphrase"
export help_mktar_10=" -q, --quiet                 suppress error messages and prompts"
export help_mktar_11=" -v, --verbose               show additional messages"
export help_mktar_12=" -V, --version               print version number and exit"
export version_mktar="mktar: 2.0"
export help_rmtar_0="Delete archives"
export help_rmtar_1="Usage: rmtar [OPTIONS] FILE.."
export help_rmtar_2="Options:"
export help_rmtar_3=" -h, --help     print this message and exit"
export help_rmtar_4=" -q, --quiet    suppress error messages"
export help_rmtar_5=" -v, --verbose  show additional messages"
export help_rmtar_6=" -V, --version  print version number and exit"
export version_rmtar="rmtar: 1.1"
export help_tarcat_0="Concatenate files in archives"
export help_tarcat_1="Usage: tar-cat [OPTIONS] FILE.."
export help_tarcat_2="Options:"
export help_tarcat_3=" -h, --help                  print this message and exit"
export help_tarcat_4=" -q, --quiet                 suppress error messages"
export help_tarcat_5=" -p=PASS, --passphrase=PASS  passphrase for decryption"
export help_tarcat_6=" -v, --verbose               show additional messages"
export help_tarcat_7=" -V, --version               print version number and exit"
export version_tarcat="tar-cat: 1.4"
export help_tarls_0="List files in an archive"
export help_tarls_1="Usage: tar-ls [OPTIONS] FILE.."
export help_tarls_2="Options:"
export help_tarls_3=" -h, --help                  print this message and exit"
export help_tarls_4=" -q, --quiet                 suppress error messages"
export help_tarls_5=" -p=PASS, --passphrase=PASS  passphrase for decryption"
export help_tarls_6=" -v, --verbose               show additional messages"
export help_tarls_7=" -V, --version               print version number and exit"
export version_tarls="tar-ls: 1.4"
export help_untar_0="Extract files from an archive"
export help_untar_1="Usage: untar [OPTIONS] FILE.."
export help_untar_2="Options:"
export help_untar_3=" -h, --help                  print this message and exit"
export help_untar_4=" -d=DIR,                     working directory"
export help_untar_5="   --from-directory=DIR,"
export help_untar_6="   --working-directory=DIR"
export help_untar_7=" -p PASS, --passphrase PASS  use plaintext passphrase"
export help_untar_8=" -q, --quiet                 suppress error messages"
export help_untar_9=" -v, --version               print version number and exit"
export version_untar="untar: 1.3"
