#!/bin/bash

name="thumbnail"
version="1.0"
read -r -d '' help_message <<-EOF
	Extract a thumbnail from a video
	Usage: thumbnail [OPTIONS] TARGET [TARGET..]
	Options:
	 -h, --help            print this message
	 -q, --quiet           suppress error messages and prompts
	 -t, --timestamp       timestamp to extract thumbnail from
	 -v, --verbose         show additional messages
	 -V, --version         print version number and exit
EOF

source /usr/local/lib/mylib.bash

positional=()
quiet=
timestamp="00:00:10.000"
verbose=
while [[ $# -gt 0 ]]; do
  case "$1" in

  -h|--help)
    help_msg
    shift
    ;;

  -q|--quiet)
    debug_msg "Setting quiet option to 1 (was ${quiet})"
    quiet=1
    shift
    ;;

  -t|--time|--timestamp)
    debug_msg "Setting timestamp option to '${2}' (was '${timestamp}')"
    timestamp="$2"
    shift; shift
    ;;

  -v|--verbose)
    debug_msg "Setting verbose option to 1 (was ${verbose})"
    verbose=1
    shift
    ;;

  -V|--version)
    version_msg
    ;;

  *)
    debug_msg "Argument '${1}' added to positional array"
    positional+=("$1")
    shift
    ;;
  esac
done

if [[ "${#positional[@]}" -eq 0 ]]; then
  usage_msg
fi

printf "$timestamp" | grep -e '^[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]$' >/dev/null 2>&1
if [[ $? -ne 0 ]]; then
  error_msg "Not a valid timestamp ('${timestamp}') - must be 'HH:MM:SS.sss'"
fi

code=0
for filename in "${positional[@]}"; do
  if [[ ! -f "$filename" ]]; then
    nonfatal_error_msg "No such file '$filename'"
    code=1
  elif [[ "$filename" = *.png ]]; then
    nonfatal_error_msg "Skipping file '$filename' - already an image"
  else
    dirname="$(dirname "$filename")"
    basename="$(basename "$filename")"
    basestub="${basename%.*}"
    debug_msg "ffmpeg -i '${basename}' -hide_banner -loglevel error -ss '${timestamp}' -frames:v 1 -update 1 '${basestub}.png'"
    (cd "$dirname" && ffmpeg -i "$basename" -hide_banner -loglevel error -ss "$timestamp" -frames:v 1 -update 1 "$basestub.png")
  fi
done

exit "$code"

