#!/bin/sh
# shellcheck disable=SC2034

name="check-x"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	Check if an X11 server is running
	Usage: check-x
EOF
)

. /usr/local/lib/myminiparse.sh

if ! /usr/bin/xset q >/dev/null 2>&1; then
  exit 1
else
  exit 0
fi

