#!/bin/sh

name="docker-get-all-services"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	List all Docker services' IDs
	Usage: docker-get-all-services
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

docker service ls --format "{{.ID}}"

