#!/bin/sh

name="pactl-volume-up"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	Increase volume (default: 10%)
	Usage: pactl-volume-up [PERCENT]
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

SINK="$(pactl-get-running-sink)"
if [ -z "$SINK" ]; then
  SINK=0
fi

if [ $# -eq 0 ]; then
  VOLUME="+10%"
elif echo "$1" | grep -F "%"; then
  VOLUME="+${1}"
else
  VOLUME="+${1}%"
fi

pactl set-sink-volume "$SINK" "$VOLUME"

