#!/bin/sh

name="qemu-test"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	Check if hardware and OS are capable of virtualization
	Usage: qemu-test
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

error_msg() {
  (>&2 /usr/bin/printf "%s: %s\n" "$name" "$1")
}

noisily_exec() {
  /usr/bin/printf "%s\n" "$1"
  $1
}

if ! LC_ALL=C lscpu | grep Virtualization >/dev/null 2>&1; then
  if [ "$quiet" -eq 0 ]; then
    error_msg "Virtualization is not supported by the CPU"
    noisily_exec "LC_ALL=C lscpu | grep Virtualization"
  fi
  exit 1
elif ! zgrep CONFIG_KVM /proc/config.gz >/dev/null 2>&1; then
  if [ "$quiet" -eq 0 ]; then
    error_msg "Virtualization is not supported by the kernel"
    noisily_exec "zgrep CONFIG_KVM /proc/config.gz"
  fi
  exit 1
elif ! lsmod | grep kvm >/dev/null 2>&1; then
  if [ "$quiet" -eq 0 ]; then
    error_msg "Kernel modules for virtualization support are not loaded"
    noisily_exec "lsmod | grep kvm"
  fi
  exit 1
fi
exit 0

