#!/bin/sh

name="rm-old"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	Delete files older than a year
	Usage: rm-old [PATH]
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

if [ -z "$1" ]; then
  path="."
else
  path="$1"
fi

find "$path" -type f -mtime +365 -delete

