#!/bin/sh

name="vpn-off"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	Stop the OpenVPN connection
	Usage: vpn-off
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

sudo killall openvpn

