#!/bin/sh

name="wg-off"
version="1.0"
help_message=$(/usr/bin/cat <<-EOF
	Stop the 'wg0' Wireguard connection
	Usage: wg-off
	Options:
	 -h, --help     print this message and exit
	 -v, --version  print version number and exit
EOF
)

. /usr/local/lib/myminiparse.sh

sudo wg-quick down wg0
sudo wg show

