#!/bin/bash

name="keytype"
version="1.0"
read -r -d '' help_message <<-EOF
	Inspect a cryptographic key for type and length
	Usage: keytype [OPTIONS] KEYFILE
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages and prompts
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/mycryptolib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

code=0

for keyfile in "${positional[@]}"; do
  if [[ ! -e "${keyfile}" ]]; then
    Fatal "no such file '${keyfile}'"
  fi

  path="$(FileAbsolute "${keyfile}")"
  if [[ -z "${path}" ]]; then
    exit 1
  fi

  desc="$(InspectOpenSSH "${path}")"
  if [[ -z "${desc}" ]]; then

    desc="$(InspectOpenPGP "${path}")"
    if [[ -z "${desc}" ]]; then

      desc="not a known key"
      code=1
    fi
  fi

  /usr/bin/printf -- '%s: %s\n' "${keyfile}" "${desc}"
done

exit "${code}"

