#!/bin/bash

name="mkhtpasswd"
version="1.0"
read -r -d '' help_message <<-EOF
	Create an Apache htpasswd file
	Usage: mkhtpasswd [OPTIONS] >>.htpasswd
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages and prompts
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

Prompt "Enter username: "
user="${response}"
if [[ -z "${user}" ]]; then
  Fatal "expected non-empty username"
fi

Prompt "Enter password: "
passwd="${response}"
if [[ -z "${passwd}" ]]; then
  Debug "using empty password"
fi

/usr/bin/printf -- '%s:%s\n' "${user}" "$(/usr/bin/openssl passwd -crypt "${passwd}")"

