#!/bin/bash

name="pgp-rm"
version="1.1"
read -r -d '' help_message <<-EOF
	Remove local OpenPGP keys
	Usage: pgp-rm [OPTIONS] KEYTHUMBNAIL..
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash
RequirePositionalArguments

code=0

for key in "${positional[@]}"; do
  if ! /usr/bin/gpg2 --delete-key "${key}"; then
    Error "failed to remove key '${key}'"
    code=1
  fi
done

exit "${code}"

