#!/bin/bash

name="vpn-off"
version="1.1"
read -r -d '' help_message <<-EOF
	Close an OpenVPN connection
	Usage: vpn-off [OPTIONS]
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages and prompts
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

RequireRoot

#NOTE: As far as I can tell, no, there isn't a better way...
/usr/bin/killall openvpn

