#!/bin/bash

last_used_config=""

_update_last_config_used() {
  /usr/bin/ed -s "$(/usr/bin/realpath --strip "${0}")" <<-EOF
	3c
	last_used_config="${1}"
	.
	w
	EOF
}

name="vpn-on"
version="1.1"
read -r -d '' help_message <<-EOF
	Open an OpenVPN connection
	Usage: vpn-on [OPTIONS] [CONFIG]
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages and prompts
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

RequireRoot

if [[ "${#positional[@]}" -gt 0 ]]; then
  Debug "updating the last-used config from '${last_used_config}' to '${positional[0]}'"
  _update_last_config_used "${positional[0]}"
  exec "${0}"
fi

if [[ -z "${last_used_config}" ]]; then
  Fatal "no configuration specified, and failed to lookup last configuration used"
fi

if ! /usr/bin/openvpn --config "${last_used_config}" --daemon; then
  Fatal "failed to connect"
fi

