#!/bin/bash

name="wg-on"
version="1.1"
read -r -d '' help_message <<-EOF
	Open the 'wg0' Wireguard connection
	Usage: wg-on
	Options:
	 -h, --help     print this message and exit
	 -q, --quiet    suppress error messages and prompts
	 -v, --verbose  show additional messages
	 -V, --version  print version number and exit
EOF

. /usr/local/lib/mylib.bash
. /usr/local/lib/myparse.bash

RequireRoot

/usr/bin/wg-quick up wg0
/usr/bin/wg show

